### ISSUE TITLE
Update intl

### ISSUE THREAD

**Issue by jsg2021** [mvhenten/format-price#1]
When the Intl.js issues (andyearnshaw/Intl.js#82 and andyearnshaw/Intl.js#99) are resolved this may need a new release.

There is a FireFox bug with Intl.js (RexExp.lastMatch is initially undefined) and its fixed in the master branch.

**Comment by reaktivo** [comment]
I noticed the package and bower.json files updated their version to 1.0.0-rc-1, how can I create the tag to make it available to bower?

**Comment by jsg2021** [comment]
Sorry, I missed your question.  I think bower is dead... they still run the registry, but are suggesting people move off of the tool.

That said, I've never used bower, so do not know how to publish it... i use npm.

**Comment by jsg2021** [comment]
I've actually starting using Intl directly.
